# Generated by Django 5.2.8 on 2025-12-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_category_name_en_category_category_name_ko_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_ko',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ko',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ko',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category_name_ko',
        ),
    ]
