# Generated by Django 5.2.8 on 2025-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_category_name_ko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
