# Generated by Django 5.2.8 on 2025-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
